### ISSUE TITLE
Doc update: Example tailwind.config.js and Dioxus.toml

### ISSUE THREAD

**Issue by mdochdev** [edger-dev/dioxus-class#1]
Hi

Thanks for all the hard work with this. I am loveing this DaisyUi integrations just a couple of minor things to help people along:
While not an ideal regex and something borrowed from houseabsolute I have crafted a script that searches all of the rust files. 

So my tailwind.config.js looks like (could probably do away with the index.html):
```
/** @type {import('tailwindcss').Config} */
module.exports = {
    content: {
        files: ["index.html", "**/*.rs"],
        extract: {
            rs: (content) => {
                const rs_to_tw = (rs) => {
                    return rs
                        .replaceAll("(", ":")
                        .replaceAll(")", "")
                        .replaceAll("_", "-");
                };
                let one_class_re = "[a-z0-9_]+(\\([a-z0-9_]+\\))*";
                let class_re = new RegExp(one_class_re , "g");
      
                let classes = [];
                classes.push(            
                    ...[...content.matchAll(class_re)].map((m) => {
                    return rs_to_tw(m[0]);
                  })
                );
                if (classes.length > 0) {
                    console.log(classes);
                }
                return classes;
            },
        },
    },
    theme: {
      extend: {},
    },
    plugins: [
      require("daisyui")
    ],
  }
```

I also manually installed tailwindcss into the dioxus-cli directories `~/.local/shared/dioxus/tools/tailwindcss/tailwindcss` (due to it not fully supporting the tools directory yet) and updated my Dioxus.toml to include this:
```
[application.tools]
tailwindcss = {input = "src/tailwind/tailwind_input.css", config="src/tailwind/tailwind.config.js" }
```
and removed the style setting. 
This means apart from having to install daisyui via npm (which would be nice to avoid), dioxus takes care of all of the heavy lifting and generates a css file which only contains classes I use. It looks like during a release it also does a minify on the css (extra bonus).

Let me know if you need more details for a readme.

**Comment by yjpark** [comment]
Thanks a lot for the comment.

Last time I checked dioxus-cli, the tool subcommand was commented out in the source code, so I didn't dig into the tailwindcss tool setting, if this works, it's pretty neat.

Thanks for the sample tailwind.config.js, there are some corner cases that current regex not covering.

- for the `0.5, 1.5, 2.5, 3.5` part in CSS, I define the constants as `_half, 1_half, 2_half, 3_half` for a clearer meaning.
- for `1/2, 1/3 ...`, I define as `1__2, 1__3` use double underscore to make it different from normal `-`
- for the `2xl:` modifier, since `2xl` is not a valid rust function name, I declare both `_2xl` and `xxl` as a hack (also add a max_xxl).
- also, for arbitrary values, I'm also use functions, e.g. `w_any, h_any` (using any! macro)

(will try to add these special cases into documents later)

This config will still be very helpful for development, but might cause some issues for production usage, not sure about how to cover these corner cases with it. I did checked the tailwindcss source code, seems the core logic been rewritten in rust already, maybe it's possible to do some tweak there for a much cleaner fix.

The static crate way is a bit more tedious, but more flexible, it's quite nice for some sites actually need a ssr output, but quite clumsy if not. I did think a bit for a better solution, not found one yet.

Anyway, thank you for trying this and giving feedback. If you have time, any improvements are welcomed, feel free to send pull request.

I'll try to setup the dioxus tools and do some experiments when got some time later.

**Comment by mdochdev** [comment]
Not sure I understand the arbitrary values comment. I am relatively new to css. But the other expressions are easily caught.
I think I still miss the `max_xxl` it will go to `max-xxl` but that doesn't sound like the intention. But for the rest it is like this:
```
                    return rs
                        // find anything that starts with _ and number and remove _ eg can have a ( or space before it
                        .replace(new RegExp("^_([0-9])", "g"), "$1")
                        // find anything _half and change to .5
                        .replaceAll("_half", ".5")
                        // find all double _ and replace with / (need to do this before single _)
                        .replaceAll("__", "/")
                        // find anything that starts with ( and replace with :
                        .replaceAll("(", ":")
                        // remove all trailing )
                        .replaceAll(")", "")
                        // replace all _ with -
                        .replaceAll("_", "-")
                        // Capture the md(_2xl) case
                        .replaceAll(":-", ":");
                };
```

I guess things like `peer` and `peer-checked` fall into the special arbitrary any group. Will look into it if I hit that issue.

**Comment by yjpark** [comment]
About the arbitrary value, here is an example from https://tailwindcss.com/docs/width#arbitrary-values

```rust
class: class!(w_any("32rem"))
```
will be converted to 

```html
class="w-[32rem]"
```

**Comment by yjpark** [comment]
Just update the crates with Dioxus 0.5.0, also using a new way to generate class, all class! macro calls are gathered by using side effects in proc_macro, I think it's much better than a text base approach.

Check [BUILD.md](https://github.com/edger-dev/dioxus-class/blob/main/BUILD.md) for more details
